name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          scope: '@reqease'
          access: 'public'

      - name: Install dependencies
        run: npm ci

      - name: Set package registry
        run: npm config set registry https://npm.pkg.github.com
      - name: GitHub package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.HICHEM_TAB_TECH_PERSONAL_TOKEN }}
      - name: Npm registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Publish the package to Github and Npm package registries
        run: npm publish
