name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          access: 'public'

      - name: Install dependencies
        run: npm ci

      - run: npm echo ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Add other environment variables as needed